.gitignore
src/cert_tool.py
src/certificates.py
src/deploy.py
src/paths.py
src/service_config/api_config.py
src/teamcity.py
src/versions.py

Also refactored TeamCity support so we can fetch artifacts based on a branch.

Generate a token signing keypair and inject it into the API container.

---

src/compose.py
src/service.py
src/versions.py

https://vimc.myjetbrains.com/youtrack/issue/VIMC-399

Links to portals don't work

---

src/deploy.py
src/service_config/api_config.py
src/versions.py

https://vimc.myjetbrains.com/youtrack/issue/VIMC-475

Pass full URL of API through to config

---

README.md
src/cli.py
src/db_users.py
src/deploy.py
src/paths.py
src/settings.py
src/versions.py

https://vimc.myjetbrains.com/youtrack/issue/VIMC-478

Give user CLI real username and password if needed

---

src/db_users.py

Create a readonly database user

---

clear-docker.sh
docker-compose.yml
src/test.py
src/versions.py
teamcity.sh

https://vimc.myjetbrains.com/youtrack/issue/VIMC-595

Run blackbox tests against montagu repository

---

staging/README.md

Is this a reasonable place for this sort of information?  Would we think to look here if we hit these problems in future?  Does this sort of non-code related change want to go through review?

Notes on troubleshooting the vms

---

.gitignore
src/backup.py
src/deploy.py
src/last_deploy.py

Naming is hard and I'm completely open to better names!

i711 Write out information about what we are deploying

---

src/versions.py

added numeric country code to demographic data

updated api & db

---

README.md
src/database.py
src/restore_db.py

Tested locally.  Once deployed I will update the (currently disabled) cron script and that will re-enable nightly restores on science

i823 - New restore script that fixes db permissions

---

src/setting_definitions/__init__.py

https://vimc.myjetbrains.com/youtrack/issue/VIMC-967

Don't require clone_reports to be set.

---

deploy.sh

Whichever of you has time to review this, please do :)

Allow one button deploy of a tag

---

scripts/release/make-release.py
scripts/release/tickets.py

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1075

i1075: Automatically tag tickets as part of release 

---

src/data_import.py

https://vimc.myjetbrains.com/youtrack/issue/VIMC-790
Must be merged after https://github.com/vimc/montagu-api/pull/167

i790: Use binary dump

---

docs/DisasterRecovery.md

This is documentation updates from working through the recovery.  Probably best to review https://github.com/vimc/montagu-recovery/pull/1 first

i423 - recovery process

---

src/database.py
src/deploy.py
src/service_config/api_config.py

One thing I wasn't sure of was whether we want to add an api specific user to the annex? I've just passed through the root user credentials...

I1126 add annex credentials to api

---

src/database.py
src/deploy.py
src/service_config/api_config.py

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1314

i1314: Also set annex hostname and port when deploying

---

docker-compose-annex.yml
docker-compose.yml
src/service_config/shiny_config.py
src/test.py
teamcity.sh

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1366
First review and merge API change

i1366: Restart Montagu on reboot 

---

scripts/setup_ssh_keys.sh
staging/README.md
staging/shared/restore

This is needed for pulling montagu-data and montagu-reports

i1315 - set up ssh on staging vms

---

src/deploy.py
src/service.py

This will reduce deployment downtime.
https://vimc.myjetbrains.com/youtrack/issue/VIMC-1570

i1570: Pull images before stopping

---

src/orderly.py

Quick cleanup before the real edits in the [next PR](https://github.com/vimc/montagu/pull/93). Part of https://vimc.myjetbrains.com/youtrack/issue/VIMC-1682

Apply all the automatic code formatting to make the warnings go away

---

src/data_import.py
src/deploy.py

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1725
First point back to master after merging https://github.com/vimc/montagu-bb8/pull/5

i1725: Move bb8 restore to while the db container is stopped

---

scripts/get_db_password.sh
scripts/setup_ssh_keys.sh
src/settings.py
staging/shared/restore

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1681
http://teamcity.montagu.dide.ic.ac.uk:8111/project.html?projectId=montagu&tab=projectOverview&branch_montagu=i1681

i1681: Replace calls to `vault auth` with `vault login` 

---

scripts/release/tag-images.py

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1900
This is a reversion of an earlier change. See the ticket for more info.

i1900: Push all tags for each image

---

src/service_config/api_config.py

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2093

i2093: Copy allow.localhost setting into reporting API container during deploy

---

src/service_config/api_config.py

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2093

i2093: A second attempt at a PR

---

src/update_versions_to_latest_master.py
src/versions.py

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2122

i2122: Improve output

---

scripts/auto-update-and-commit.sh
src/update_versions_to_latest_master.py
src/versions.py

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2124
First merge https://vimc.myjetbrains.com/youtrack/issue/VIMC-2122

i2124: Improve commit message for auto-update tool 

---

src/orderly.py

This introduces one small deployment change to bring the orderly
database up to date with any migrations.

i2278: Update orderly containers to 0.5.3

---

settings/latest.json

Added vault address

---

src/orderly.py

Can we test this with your new vagrant config Emma? Using any unknown server name should have the same effect as previously using teamcity now

i2516: More relaxed orderly api server configuration

---

.gitmodules
docker-compose.yml
scripts/release/tag-images.py
src/compose.py
src/deploy.py
src/service.py
src/service_config/__init__.py
src/service_config/shiny_config.py
src/versions.py

This seems to pass ok on teamcity, but it's a bit tricky to know for sure with that test failure

i2546: remove shiny from deploy

---

src/service.py
static/model-documentation/2019/config.csv

Also:
https://github.com/vimc/montagu-static/pull/3
and
https://github.com/vimc/montagu-proxy/pull/19

I2616 - just host model documentation

---

src/orderly.py

Merge after https://github.com/vimc/montagu-reports/pull/273

i2495: Add latest to the set of known orderly repos

---

src/deploy.py
src/service_config/api_config.py

Inject webhook from vault into the api config. I have already written the value into the vault.

VIMC-2986 support notifying Slack when estimates uploaded

---

ReleaseProcess.md
scripts/release/make-release.py

Tidies up deploy/release documentation after some of the sticking points encountered running this myself
Also added a page to the wiki which points to this https://mrc-ide.myjetbrains.com/youtrack/articles/VIMC-A-27/Montagu-redeploy

Update deploy docs

---

docker-compose.yml

See https://mrc-ide.myjetbrains.com/youtrack/issue/VIMC-4230 for discussion of the building of the static sever image itself

vimc-4320 use docker hub for static image

---

docker-compose.yml
src/database.py

Once https://github.com/vimc/montagu-db/pull/149 is merged the db submodule can be pointed back to master

vimc-4229 use db image from docker hub

---

container_config/task_queue/test_diagnostic_reports.yml
src/generate_real_diagnostic_reports_config.py
src/service_config/task_queue_config.py
src/test.py

Also change from address to `montagu-help`, so that it can be replied to.

vimc-4250 add new email subject for diagnostic reports

---

src/generate_real_diagnostic_reports_config.py

Hi Alex and Emma - I've updated the emails in the PI emails section. I've also added 3 new groups (IVI-Kim, JHU-Lee and Yale-Pitzer) and emails for them. Could you check my syntax is OK? thanks!

updated modeller emails and group names

---

src/generate_real_diagnostic_reports_config.py

added "Imperial-test user" and email for the PI (t.vuong@imperial.ac.uk)

added Imperial test user group and email

---

scripts/copy-vis-tool.sh

Hopefully this is the last one for paper 1...
This is actually already live on production: https://montagu.vaccineimpact.org/2020/visualisation/

vimc-4536 Update paper 1 datavis tool location

---

src/test.py

Requires https://github.com/vimc/orderly/pull/271 and will fail until that is merged

Create git directory for orderly

---

scripts/release/tickets.py

This has been tested by creating [v2.32.0](https://mrc-ide.myjetbrains.com/youtrack/issues?q=Fixed%20in%20build:%20v2.32.0)
New API is rather less ergonomic than its predecessor...

VIMC-4798 Update release script to latest YouTrack API

---

src/database.py

Increase timeout to 2h to ensure some headroom

VIMC-4821 Increase database connection timeout

---

container_config/task_queue/real_diagnostic_reports.yml

Regenerate the config file from the script changes made in https://github.com/vimc/montagu/pull/211

vimc-4841_regen Regenerate config file from updated script

---

src/generate_real_diagnostic_reports_config.py

UND-Perkins: Quan Tran Minh
PSU-Ferrari: Sarah Hauryski

added two new recipients

---

src/generate_real_diagnostic_reports_config.py

Updated Amy Winter's email, removed John Huber & Hira Tanvir

updated recipients

---

src/generate_real_diagnostic_reports_config.py

removed Kiesha Prem & Petra Klepac, added Megan Auzenbergs

updated LSHTM-Clark receipients

---

docker-compose.yml
src/service_config/api_config.py

Configure the API upload volume. Deployed on UAT and tested manually by uploading a burden estimate file, waiting overnight for it to be deleted.

vimc-6329 configure upload dir for api

---

README.md
certs/support/README.md
scripts/get_db_password.sh
settings/latest.json
settings/production.json
settings/science.json
settings/uat.json
src/settings.py
src/vimc-robot-keygen.sh

* update vault addr
* update config
* point to updated bb8
Should also merge https://github.com/vimc/bb8/pull/54 (and then can point back to bb8 master here)

vimc-6759 updates for new vault

---

settings/buildkite.json
settings/dev.json
settings/latest.json
settings/production.json
settings/science.json
settings/uat.json
src/service_config/task_queue_config.py
src/test.py

Needs to be merged and deployed alongside https://github.com/vimc/orderly-web/pull/506 and https://github.com/vimc/montagu-task-queue/pull/32

vimc-6928 update config and test image
