vimc/montagu

- src/backup.py
After merging [the PR for the submodule](https://github.com/vimc/montagu-backup/pull/1) you should update this repo (or ask me to) so that it points at master in the submodule.
https://vimc.myjetbrains.com/youtrack/issue/VIMC-489
> Add Orderly volume to backup config

- src/deploy.py
- src/git.py
- src/setting_definitions/__init__.py
- teamcity-settings.json
The idea here is to prevent deploying into production a system that
is untagged and/or has a dirty git status (the latter is most
commonly triggered by a submodule being out of date - seen with the
backup module).
We only want this on production really.  We detect this by looking
to see if 'backup' is selected (this will be false for all but
production).
> I632 - check deploy environment is clean

- src/database.py
This should be straightforward but will stop leaving around unneeded containers after stopping montagu
```
rich@wpia-dide136 ~/Documents/Projects/epi/vimc/montagu $ docker ps -a
CONTAINER ID        IMAGE                                                       COMMAND                  CREATED             STATUS                      PORTS                    NAMES
d7ba961b4bc6        docker.montagu.dide.ic.ac.uk:5000/montagu-migrate:6d203bf   "flyway migrate -u..."   13 minutes ago      Exited (0) 13 minutes ago                            unruffled_torvalds
```
> i704 Clean up migration container on exit

- src/deploy.py
- src/orderly.py
This fixes the bug that Martin found; it's not just the `is_first_time`
setting I need to pass through but also the persist data.
> i952 Initialise the orderly volume on consecutive minimal deploys

- src/service.py
As documented in VIMC-805, the orderly container will respond quickly
to an interrupt, but not to whatever docker stop (via docker-compose stop)
is sending.  This is (presumably) a limitation of httpuv and not something
I can see how to work around at the R level.  So instead we send an
interrupt signal (SIGINT) just before the stop, and that seems to bring
things down much more quicky.
> i805 - Send orderly container an interrupt before stopping

- scripts/release/make-release.py
This makes the git commit message conform to the conventional format,
with a blank line following the title before the body.  This is
expected by tooling around git (including things like `git log --oneline`)
which will run all the lines together if the blank line is not there.
> i1063 - Add blank line in release message

- src/deploy.py
- src/notify.py
- src/requirements.txt
- src/setting_definitions/__init__.py
- teamcity-settings.json
This will hopefully reduce the number of "is montagu being deployed" or "why is my connection not working" questions.  Uses slack incoming webhooks, with the address stored in the vault.
This adds two more settings (I don't think they can sensibly be combined into one) - the channel to post into and the name of the deployment.
To test, just set these as something like
```
"notify_channel": "montagu-deploy",
"instance_name": "local (rich)",
```
and on deploy it will print a message as deployment starts, previous versions are brought down and on completion or error.  An example is in #montagu-deploy now
> i1052 - Post in slack as deploy begins/ends

- RELEASE_LOG.md
- ReleaseProcess.md
- docker-compose-annex.yml
- docker-compose.yml
- scripts/release/helpers.py
- scripts/release/make-release.py
- scripts/release/tag-images.py
- src/compose.py
- src/docker_helpers.py
This PR does a couple of related things:
* `scripts/release/tag-images.py` coordinates tagging images that were used as part of a release and publishing those onto docker hub
* changes to allow deployment using these issues (this removes almost all of our `docker.montagu.dide.ic.ac.uk:5000` strings throughout the code
The idea is we'll have all images that were part of a release lodged on docker hub, tagged with both version numbers and with the git sha.  Eventually we might want to allow using the versioned tags in deployment too (rather than the sha).
In order to push to docker hub you will need to make an account and then have me add you to the vimc account. Anyone can pull the images.
Commit 19eb21d4102049c62ae3bc6392ed8a1b11458d4a introduces changes to the way that the release script …
> i979 - deploy from docker hub

- RELEASE_LOG.md
- scripts/release/make-release.py
- scripts/release/tickets.py
Fixes bug with branches that don't have tickets associated with them.
Simplified logic to treat branches as just one of:
1. a branch that *does* have a ticket associated with it, in which case we use that info in the release log
2. a branch that does *not* have a ticket associated with it, in which case we print a warning to the console,  and if the user continues list it in the 'other branches' section of the release log
i.e. don't bother distinguishing between the cases where a branch matches the regex but fails the issue lookup, and where a branch fails the regex
> I1092 - bug with branches that fail issue lookup

- src/restore_db.py
- src/versions.py
We will *eventually* get this running as a cron job.
The changes in versions.py make things a little less sensitive to working directories.  The other changes are mostly about getting the notifier working and creating test users if required
> i1096 - fix db restore without redeploy on science

- deploy.py
- scripts/release/helpers.py
- scripts/release/make-release.py
- scripts/release/release_tag.py
- scripts/release/tag-images.py
This is approach no 1 to fix [VIMC-1175](https://vimc.myjetbrains.com/youtrack/issue/VIMC-1175). It is quite a big change, as it moves release tag into a class, but I think the resulting logic is easier to understand and maintain. It gives us nice things, like automatic stringification, and total ordering.
See also #61.
> Use latest release tag (class refactor)

- docker-compose.yml
- src/guidance_report_versions
- src/service.py
- src/service_config/contrib_portal_config.py
Have confirmed this works locally, i.e. the report paths are valid and result in exposing:
`../contribution/guidance/child-mortality.html`
`../contribution/guidance/over80.html`
`../contribution/guidance/kosovo_demography.html`
`../contribution/guidance/marshall_demography.html`
`../contribution/guidance/tuvalu_demography.html`
One question I have here is whether the info in these reports is at all sensitive?
With the templates we don't worry about them being publicly viewable because they contain no data; I don't know if that is true here or whether we'd want to lock them down to logged in users (I guess we'd have to use Caddy if so!!)
@weshinsley do you know the answer?
> I1434 - copy guidance reports into contrib container

- README.md
- docker-compose-annex.yml
- docker-compose.yml
Please note - this requires docker-compose 1.17.0 or greater.  If you do not have that version you will get an error like:
```
The Compose file './../docker-compose.yml' is invalid because:
Additional properties are not allowed ('x-logging' was unexpected)
You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version ("2.0", "2.1", "3.0", "3.1", "3.2") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
I have not added logging to the (fake) annex because we don't use that in production.  I can add it if needed but it will …
> i1466: logging via systemd

- scripts/release/tickets.py
If one branch doesn't have a ticket, should `continue` rather than `break` the loop.
> i1430 - Release script doesn't always tag in YouTrack

- staging/Vagrantfile
- RAM increased to avoid an OOM error on a science import 3 * 16 GB = 48 of the 125 on the machine, leaving 77 for the on-metal docker (vault, registry) and for the four CI machines
- Disk increased to 900GB, reflecting the size of production's disk
> i1675: Increase size of ram and disks

- .gitmodules
- src/backup.py
- src/bb8_backup.py
- src/data_import.py
- src/deploy.py
- src/orderly.py
- src/restore_db.py
- src/setting_definitions/__init__.py
- teamcity-settings.json
https://vimc.myjetbrains.com/youtrack/issue/VIMC-1682
This also adds the ability to restore from bb8 as the initial data source. But I've only got bb8 working for the orderly volume, which is the easy bit. There are other tickets for database backup via barman, and database restore from bb8.
First merge https://github.com/vimc/montagu/pull/92 and https://github.com/vimc/bb8/pull/20, and update the montagu-bb8 submodule.
> i1682: Install and schedule bb8 during deploy 

- src/notify.py
Duplicated from comment, provides the rationalle
> There are two ways that this can fail: (1) the slack server
can respond with an error (e.g., if the incoming webhook is
removed or expires, the slack server is down for
maintenence but still largely functioning, etc).  In that
case we'll get a nice HTTP error code and we can just print
that.  (2) the communication with the server fails because
the network is down, slack is really down, etc.  In that
case requests will Raise and that needs catching.
> In either case, as soon as one request fails, don't send
future notifications as they're highly unlikely to work,
and if they're timing out that'll get tedious.
> i1906: Gracefully allow slack notification to fail

- docker-compose.yml
- src/compose.py
- src/setting_definitions/__init__.py
- src/settings.py
- teamcity-settings.json
https://vimc.myjetbrains.com/youtrack/issue/VIMC-2219
I also:
* Made `montagu-deploy.json` more readable, by sorting indenting and sorting the keys
* Added defaults to a bunch of the settings, to make it easier to quickly set up a local test instance from scratch (which is when I am most often repeatedly answering these questions)
> i2219: Enable production db config

- src/requirements.txt
Used in two places:
* src/notify.py for slacking us with changes
* src/teamcity.py for getting test data
The notify one won't be tested until we deploy, but the test data one suggests this is all reasonably ok, as we're passing on TC.
> i2378: Upgrade requests

- scripts/check-settings
- settings/production.json
- settings/restore-test.json
- settings/science.json
- src/settings.py
This needs enabling on TC after merge.  Main script is
`./scripts/check-settings`
To test, try working on 5fcfc8e where the script errors on 3 settings files; e12cb9b fixes this
> i2486: validate settings

- README.md
- ReleaseProcess.md
- deploy.py
- src/deploy.py
Most of the changes here are documentation changes, and then updating to include changes in bb8 and montagu-bb8; merge these up the dependency chain (bb8, then montagu-bb8 then montagu), updating submodule references as appropriate
https://github.com/vimc/bb8/pull/47 & https://github.com/vimc/montagu-bb8/pull/7
> i1747: Remove need for sudo from deploy

- clear-docker.sh
- src/compose.py
- src/deploy.py
- src/service.py
Updates the proxy which will now point to the version that proxies OW. Changed the "stop" logic to stop containers rather than bringing down the network.
> VIMC-2947 support switch from reporting portal to orderly web

- docker-compose.yml
Science have hit a problem where the SQL code generated by dbplyr generates parallel aggregate queries and that runs the db out of shared memory.  This question here is exactly the problem that we have: https://meta.discourse.org/t/pg-throws-could-not-resize-shared-memory-segment-error/84744
The solution is to increase the shared memory available to the container via a docker option.  After deploying a version with this change we should be able to do
```
docker exec -it montagu_db_1 df -h /dev/shm
```
and see a much larger number than 64M in Avail. On my machine with the dev settings:
```
$ docker exec -it montagu_db_1 df -h /dev/shm
Filesystem      Size  Used Avail Use% Mounted on
shm             512M  8.0K  512M   1% /dev/shm
```
on production at the moment:
```
$ docker exec -it …
```
> vimc-3496: Increase shared memory size

- .gitignore
- scripts/copy-vis-tool.sh
This PR updates the proxy to include vimc-3908 (https://github.com/vimc/montagu-proxy/pull/50) and adds a script to copy the vis tool into place.
Merge the montagu-proxy PR first and update the commit in the submodule.
Currently deployed (with dummy report) on uat:
https://support.montagu.dide.ic.ac.uk:10443/visualisation/2020/
> vimc-3920: Add vis tool (manually)

- docker-compose.yml
- src/test.py
The web portals no longer exist at the custom registry, as we're slowly retiring it. So this points the docker compose file to the public docker hub for these images.
> Partially retiring the custom docker registry

- src/deploy.py
So it seems that cloning the static server is going to break the deploy (for still mysterious reasons), so it will be a happy coincidence if it turns out that we can retire the static server at this point. 
This is a temporary fix to ensure that we can continue to test other stuff on uat - for some reason the configuration of the static server was being switched on the guidance reports setting rather than the static files setting. I've just updated to use that setting instead. 
We ALSO need to either retire static server or fix it!
> Only configure static server if configured to copy files

- docker-compose.yml
Should be merged along with https://github.com/vimc/montagu-proxy/pull/54
> vimc-4228 use docker hub for proxy image

- src/service_config/task_queue_config.py
Again, a bit tricky to test as should only occur in production. Can be tested locally by setting `fake_smtp` to false in `montagu-deploy.json` before running `src/deploy.py`, then checking the contents of the deployed config file with `docker exec montagu_task-queue_1 cat config/config.yml`
> vimc-4224 Provide smtp credetials for real smtp server

- src/generate_real_diagnostic_reports_config.py
I have not committed the regenerated config, as we want this to be empty for now. Should be ok to regenerate once https://github.com/vimc/montagu/pull/188 is merged
> vimc-4295 Added timeout to generate diagnostic report config script

- ReleaseProcess.md
- scripts/release/make-release.py
- scripts/release/tag-images.py
Apparently we haven't done a proper montagu release since we removed the private docker registry. This branch simplifies the `tag-images` script by removing the option to publish to the vimc registry - because that's what it always uses now. Also updates instructions to user.
> vimc-4475 Remove use of private docker registry from release scripts

- scripts/copy-vis-tool.sh
I think this should be the last PR for the paper 1 datavis tool! Just updates the report version to this, run on production yesterday with the latest changes (paper link, new colours, gavi73): https://montagu.vaccineimpact.org/reports/report/paper-first-public-app/20210119-181839-c82a6c22
> vimc-4438 Updated public datavis tool version

- scripts/copy-vis-tool.sh
- src/service_config/task_queue_config.py
..also opportunistically fixing the sender email address for the task runner. 
This has been deployed to uat (with script modified to match actual report versions on uat) along with corresponding proxy branch: https://support.montagu.dide.ic.ac.uk:10443/2021/visualisation/
> vimc-4514 Copy datavis tool for paper 2

- src/service_config/api_config.py
Required for vimc/montagu-api#457
URL has been added to Vault under the relevant path. It includes auth token.
Slack appears to also be used for notifications of new deploys(?) but that uses a different secret
> VIMC-4567 Migrate burden estimate upload feed to Teams

- ci.sh
- src/requirements.txt
Previous version will not work with python 3.8
This is required for https://github.com/vimc/montagu-machine/pull/24
> Update required version of psycopg2

- docker-compose.yml
- src/service_config/api_config.py
- src/service_config/task_queue_config.py
This branch:
- adds a volume to docker compose, `burden_estimate_files`, which is used by the api and task queue containers 
- Configures the task queue to use a minimum file age of 1 hour when archiving files. 
- Opens the permissions to the volume when the api starts, so that it is accessible to the task queue worker user
Deployed to UAT, or you can test locally with `src/deploy.py`. 
You can run the task with:
`curl -X POST -d '{"args":["burden_estimate_files"]}' http://localhost:5555/api/task/send-task/archive_folder_contents`
Any files in the volume (at the top level) which are older than 1 hour should be deleted. I've left a file, `test.txt`, in the volume on UAT, to make this easy to test, or you could edit the config file in the task queue container to drop the minimum file age. …
> vimc-6327 Add burden estimate files volume
